sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t suhasappa/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true suhasappa/docker-react npm run test